"""add enrollment table

Revision ID: 2917cc901cab
Revises: cf1e84e1acfd
Create Date: 2025-11-02 20:30:17.163444

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2917cc901cab"
down_revision: str | Sequence[str] | None = "cf1e84e1acfd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrollment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("enrollment_date", sa.Date(), nullable=False),
        sa.Column("unenrollment_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "status IN ('active', 'completed', 'dropped')", name="ck_enrollment_status"
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_id", "course_id", name="uq_enrollment_student_course"
        ),
    )
    op.create_index(
        op.f("ix_enrollment_course_id"), "enrollment", ["course_id"], unique=False
    )
    op.create_index(
        op.f("ix_enrollment_status"), "enrollment", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_enrollment_student_id"), "enrollment", ["student_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_enrollment_student_id"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_status"), table_name="enrollment")
    op.drop_index(op.f("ix_enrollment_course_id"), table_name="enrollment")
    op.drop_table("enrollment")
    # ### end Alembic commands ###
