"""Add PageAnnotation model for PDF annotations

Revision ID: 2fa281060376
Revises: d4bfc60b785e
Create Date: 2026-08-31 15:37:06.850606

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2fa281060376"
down_revision = "d4bfc60b785e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "page_annotation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["document.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "page_number"),
    )
    with op.batch_alter_table("page_annotation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_page_annotation_document_id"), ["document_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("page_annotation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_page_annotation_document_id"))

    op.drop_table("page_annotation")
    # ### end Alembic commands ###
