"""Add submission and document tables

Revision ID: 3dbcb98724cd
Revises: b9870ca5693c
Create Date: 2026-01-06 01:19:59.147386

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3dbcb98724cd'
down_revision: str | Sequence[str] | None = 'b9870ca5693c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('submission_type', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('submitted', 'reviewed', 'graded', 'returned')", name='ck_submission_status'),
    sa.CheckConstraint("submission_type IN ('document', 'assignment', 'exam_answer', 'email_attachment')", name='ck_submission_type'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_submission_enrollment', 'submission', ['enrollment_id'], unique=False)
    op.create_index('idx_submission_exam', 'submission', ['exam_id'], unique=False)
    op.create_index('idx_submission_status', 'submission', ['status'], unique=False)
    op.create_index(op.f('ix_submission_enrollment_id'), 'submission', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_submission_exam_id'), 'submission', ['exam_id'], unique=False)
    op.create_index(op.f('ix_submission_status'), 'submission', ['status'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('idx_document_file_type', 'document', ['file_type'], unique=False)
    op.create_index('idx_document_submission', 'document', ['submission_id'], unique=False)
    op.create_index(op.f('ix_document_submission_id'), 'document', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_submission_id'), table_name='document')
    op.drop_index('idx_document_submission', table_name='document')
    op.drop_index('idx_document_file_type', table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_submission_status'), table_name='submission')
    op.drop_index(op.f('ix_submission_exam_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_enrollment_id'), table_name='submission')
    op.drop_index('idx_submission_status', table_name='submission')
    op.drop_index('idx_submission_exam', table_name='submission')
    op.drop_index('idx_submission_enrollment', table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
