"""Add student table

Revision ID: 70a94442bf87
Revises: 3684a0b49ad3
Create Date: 2025-11-02 18:36:06.508066

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "70a94442bf87"
down_revision: Union[str, Sequence[str], None] = "3684a0b49ad3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
