"""Add exam and exam_component tables

Revision ID: 79883820bd23
Revises: 2917cc901cab
Create Date: 2025-12-14 02:00:06.420230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79883820bd23'
down_revision: Union[str, Sequence[str], None] = '2917cc901cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exam_type', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_course', 'exam', ['course_id'], unique=False)
    op.create_index('idx_exam_due_date', 'exam', ['due_date'], unique=False)
    op.create_index('idx_exam_type', 'exam', ['exam_type'], unique=False)
    op.create_table('exam_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_component_exam', 'exam_component', ['exam_id'], unique=False)
    op.create_index('idx_exam_component_order', 'exam_component', ['exam_id', 'order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_exam_component_order', table_name='exam_component')
    op.drop_index('idx_exam_component_exam', table_name='exam_component')
    op.drop_table('exam_component')
    op.drop_index('idx_exam_type', table_name='exam')
    op.drop_index('idx_exam_due_date', table_name='exam')
    op.drop_index('idx_exam_course', table_name='exam')
    op.drop_table('exam')
    # ### end Alembic commands ###
