"""Add grading system tables

Revision ID: 9b633f2b48b1
Revises: 3dbcb98724cd
Create Date: 2026-01-06 13:39:18.413104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b633f2b48b1'
down_revision: Union[str, Sequence[str], None] = '3dbcb98724cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grading_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grading_scale_university', 'grading_scale', ['university_id'], unique=False)
    op.create_index(op.f('ix_grading_scale_university_id'), 'grading_scale', ['university_id'], unique=False)
    op.create_table('grade_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('grade_value', sa.Float(), nullable=False),
    sa.Column('grade_label', sa.String(length=50), nullable=False),
    sa.Column('min_percentage', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('min_percentage >= 0 AND min_percentage <= 100', name='ck_threshold_percentage'),
    sa.ForeignKeyConstraint(['scale_id'], ['grading_scale.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_id', 'grade_value', name='uq_threshold_scale_grade')
    )
    op.create_index('idx_threshold_percentage', 'grade_threshold', ['min_percentage'], unique=False)
    op.create_index('idx_threshold_scale', 'grade_threshold', ['scale_id'], unique=False)
    op.create_index(op.f('ix_grade_threshold_scale_id'), 'grade_threshold', ['scale_id'], unique=False)
    op.create_table('exam_component',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_points > 0', name='ck_component_max_points'),
    sa.CheckConstraint('weight > 0 AND weight <= 100', name='ck_component_weight'),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_component_exam', 'exam_component', ['exam_id'], unique=False)
    op.create_index('idx_component_order', 'exam_component', ['exam_id', 'order'], unique=False)
    op.create_index(op.f('ix_exam_component_exam_id'), 'exam_component', ['exam_id'], unique=False)
    op.create_table('grade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=True),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('grade_value', sa.Float(), nullable=True),
    sa.Column('grade_label', sa.String(length=50), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=False),
    sa.Column('graded_by', sa.String(length=100), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('percentage >= 0 AND percentage <= 100', name='ck_grade_percentage'),
    sa.CheckConstraint('points >= 0', name='ck_grade_points'),
    sa.ForeignKeyConstraint(['component_id'], ['exam_component.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollment.id'], ),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', 'exam_id', 'component_id', name='uq_grade_enrollment_exam_component')
    )
    op.create_index('idx_grade_component', 'grade', ['component_id'], unique=False)
    op.create_index('idx_grade_enrollment', 'grade', ['enrollment_id'], unique=False)
    op.create_index('idx_grade_exam', 'grade', ['exam_id'], unique=False)
    op.create_index('idx_grade_final', 'grade', ['is_final'], unique=False)
    op.create_index(op.f('ix_grade_component_id'), 'grade', ['component_id'], unique=False)
    op.create_index(op.f('ix_grade_enrollment_id'), 'grade', ['enrollment_id'], unique=False)
    op.create_index(op.f('ix_grade_exam_id'), 'grade', ['exam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grade_exam_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_enrollment_id'), table_name='grade')
    op.drop_index(op.f('ix_grade_component_id'), table_name='grade')
    op.drop_index('idx_grade_final', table_name='grade')
    op.drop_index('idx_grade_exam', table_name='grade')
    op.drop_index('idx_grade_enrollment', table_name='grade')
    op.drop_index('idx_grade_component', table_name='grade')
    op.drop_table('grade')
    op.drop_index(op.f('ix_exam_component_exam_id'), table_name='exam_component')
    op.drop_index('idx_component_order', table_name='exam_component')
    op.drop_index('idx_component_exam', table_name='exam_component')
    op.drop_table('exam_component')
    op.drop_index(op.f('ix_grade_threshold_scale_id'), table_name='grade_threshold')
    op.drop_index('idx_threshold_scale', table_name='grade_threshold')
    op.drop_index('idx_threshold_percentage', table_name='grade_threshold')
    op.drop_table('grade_threshold')
    op.drop_index(op.f('ix_grading_scale_university_id'), table_name='grading_scale')
    op.drop_index('idx_grading_scale_university', table_name='grading_scale')
    op.drop_table('grading_scale')
    # ### end Alembic commands ###
