"""Add exam table

Revision ID: b9870ca5693c
Revises: 2917cc901cab
Create Date: 2025-12-14 23:41:41.413665

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9870ca5693c"
down_revision: str | Sequence[str] | None = "2917cc901cab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exam",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("exam_date", sa.Date(), nullable=False),
        sa.Column("max_points", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_exam_course", "exam", ["course_id"], unique=False)
    op.create_index("idx_exam_date", "exam", ["exam_date"], unique=False)
    op.create_index(op.f("ix_exam_course_id"), "exam", ["course_id"], unique=False)
    op.create_index(op.f("ix_exam_exam_date"), "exam", ["exam_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_exam_exam_date"), table_name="exam")
    op.drop_index(op.f("ix_exam_course_id"), table_name="exam")
    op.drop_index("idx_exam_date", table_name="exam")
    op.drop_index("idx_exam_course", table_name="exam")
    op.drop_table("exam")
    # ### end Alembic commands ###
