"""add course table

Revision ID: cf1e84e1acfd
Revises: 70a94442bf87
Create Date: 2025-11-02 19:29:33.661371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf1e84e1acfd"
down_revision: Union[str, Sequence[str], None] = "70a94442bf87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("student_id", sa.String(length=8), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("program", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_student_email", "student", ["email"], unique=False)
    op.create_index(
        "idx_student_name", "student", ["last_name", "first_name"], unique=False
    )
    op.create_index("idx_student_student_id", "student", ["student_id"], unique=False)
    op.create_index(op.f("ix_student_email"), "student", ["email"], unique=True)
    op.create_index(
        op.f("ix_student_last_name"), "student", ["last_name"], unique=False
    )
    op.create_index(
        op.f("ix_student_student_id"), "student", ["student_id"], unique=True
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("semester", sa.String(length=10), nullable=False),
        sa.Column("university_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["university_id"],
            ["university.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "university_id",
            "semester",
            "slug",
            name="uq_course_university_semester_slug",
        ),
    )
    op.create_index("idx_course_semester", "course", ["semester"], unique=False)
    op.create_index("idx_course_university", "course", ["university_id"], unique=False)
    op.create_index(op.f("ix_course_semester"), "course", ["semester"], unique=False)
    op.create_index(
        op.f("ix_course_university_id"), "course", ["university_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_course_university_id"), table_name="course")
    op.drop_index(op.f("ix_course_semester"), table_name="course")
    op.drop_index("idx_course_university", table_name="course")
    op.drop_index("idx_course_semester", table_name="course")
    op.drop_table("course")
    op.drop_index(op.f("ix_student_student_id"), table_name="student")
    op.drop_index(op.f("ix_student_last_name"), table_name="student")
    op.drop_index(op.f("ix_student_email"), table_name="student")
    op.drop_index("idx_student_student_id", table_name="student")
    op.drop_index("idx_student_name", table_name="student")
    op.drop_index("idx_student_email", table_name="student")
    op.drop_table("student")
    # ### end Alembic commands ###
