"""Add exam table

Revision ID: ebeeb698d825
Revises: 2917cc901cab
Create Date: 2025-12-14 01:46:02.554620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebeeb698d825'
down_revision: Union[str, Sequence[str], None] = '2917cc901cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('max_points', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('max_points > 0', name='ck_exam_positive_max_points'),
    sa.CheckConstraint('weight >= 0.0 AND weight <= 1.0', name='ck_exam_weight_range'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exam_course', 'exam', ['course_id'], unique=False)
    op.create_index(op.f('ix_exam_course_id'), 'exam', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_course_id'), table_name='exam')
    op.drop_index('idx_exam_course', table_name='exam')
    op.drop_table('exam')
    # ### end Alembic commands ###
