"""
University routes blueprint.

This module provides web routes for managing universities through the Flask interface.
"""

import logging
from typing import Any, cast

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required
from sqlalchemy.exc import SQLAlchemyError

from app import db
from app.forms.university import UniversityForm
from app.models.course import Course
from app.models.enrollment import Enrollment
from app.models.exam import Exam
from app.models.student import Student
from app.models.university import University
from app.services.university_service import UniversityService
from app.utils.auth import admin_required
from app.utils.pagination import paginate_query

# Configure logging
logger = logging.getLogger(__name__)

# Create blueprint
bp = Blueprint("university", __name__, url_prefix="/universities")


@bp.route("/")
@login_required
def index() -> str:
    """
    List all universities with optional search and pagination.

    Query parameters:
        search: Optional search term to filter by name or slug
        page: Page number (default: 1)

    Returns:
        Rendered template with paginated list of universities
    """
    search_term = request.args.get("search", "").strip()
    service = UniversityService()

    try:
        # Build query using service's query method
        query = service.query(University)

        if search_term:
            search_pattern = f"%{search_term}%"
            query = query.filter(
                (University.name.ilike(search_pattern))
                | (University.slug.ilike(search_pattern))
            )

        query = query.order_by(University.name)
        pagination = paginate_query(query, per_page=20)

        return render_template(
            "university/list.html",
            universities=pagination.items,
            pagination=pagination,
            search_term=search_term,
        )

    except SQLAlchemyError as e:
        logger.error(f"Database error while listing universities: {e}")
        flash("Error loading universities. Please try again.", "error")
        return render_template(
            "university/list.html", universities=[], pagination=None, search_term=""
        )


@bp.route("/<int:university_id>")
@login_required
def show(university_id: int) -> str | Any:
    """
    Show details for a specific university.

    Args:
        university_id: University ID

    Returns:
        Rendered template with university details or 404
    """
    service = UniversityService()

    try:
        university = service.get_university(university_id)

        if not university:
            flash(f"University with ID {university_id} not found.", "error")
            return redirect(url_for("university.index"))

        courses = (
            db.session.query(Course)
            .filter(Course.university_id == university.id)
            .order_by(Course.semester.desc(), Course.name)
            .all()
        )
        students_count = (
            db.session.query(Student)
            .join(Enrollment)
            .join(Course)
            .filter(Course.university_id == university.id)
            .filter(Student.deleted_at.is_(None))
            .distinct(Student.id)
            .count()
        )
        exams_count = (
            db.session.query(Exam)
            .join(Course)
            .filter(Course.university_id == university.id)
            .count()
        )

        return render_template(
            "university/detail.html",
            university=university,
            courses=courses,
            students_count=students_count,
            exams_count=exams_count,
        )

    except SQLAlchemyError as e:
        logger.error(f"Database error while fetching university: {e}")
        flash("Error loading university details. Please try again.", "error")
        return redirect(url_for("university.index"))


@bp.route("/new", methods=["GET", "POST"])
@login_required
def new() -> str | Any:
    """
    Create a new university.

    GET: Show form
    POST: Create university and redirect to detail page

    Form fields:
        name: University name (required)
        slug: URL-friendly identifier (optional, auto-generated if empty)

    Returns:
        Rendered form template (GET) or redirect to detail page (POST)
    """
    form = UniversityForm()
    service = UniversityService()

    if form.validate_on_submit():
        try:
            # Create new university using service
            university = service.add_university(
                name=cast(str, form.name.data),
                slug=form.slug.data,  # slug is auto-generated by service if empty
            )

            logger.info(f"Created university: {university.name} ({university.slug})")
            flash(f"University '{university.name}' created successfully.", "success")
            return redirect(url_for("university.show", university_id=university.id))

        except ValueError as e:
            logger.error(f"Validation error while creating university: {e}")
            flash(str(e), "error")

        except SQLAlchemyError as e:
            logger.error(f"Database error while creating university: {e}")
            flash("Error creating university. Please try again.", "error")

    # Display form validation errors
    for _field, errors in form.errors.items():
        for error in errors:
            flash(error, "error")

    return render_template("university/form.html", university=None, form=form)


@bp.route("/<int:university_id>/edit", methods=["GET", "POST"])
@login_required
def edit(university_id: int) -> str | Any:
    """
    Edit an existing university.

    GET: Show edit form
    POST: Update university and redirect to detail page

    Args:
        university_id: University ID

    Form fields:
        name: University name (required)
        slug: URL-friendly identifier (required)

    Returns:
        Rendered form template (GET) or redirect to detail page (POST)
    """
    service = UniversityService()

    try:
        university = service.get_university(university_id)

        if not university:
            flash(f"University with ID {university_id} not found.", "error")
            return redirect(url_for("university.index"))

        form = UniversityForm(university=university, obj=university)

        if form.validate_on_submit():
            try:
                # Update using service
                university = service.update_university(
                    university_id=university_id,
                    name=form.name.data,
                    slug=form.slug.data,
                )

                if university:
                    logger.info(
                        f"Updated university: {university.name} ({university.slug})"
                    )
                    flash(
                        f"University '{university.name}' updated successfully.",
                        "success",
                    )
                    return redirect(
                        url_for("university.show", university_id=university.id)
                    )

            except ValueError as e:
                logger.error(f"Validation error while updating university: {e}")
                flash(str(e), "error")

            except SQLAlchemyError as e:
                logger.error(f"Database error while updating university: {e}")
                flash("Error updating university. Please try again.", "error")

        # Display form validation errors
        for _field, errors in form.errors.items():
            for error in errors:
                flash(error, "error")

        return render_template("university/form.html", university=university, form=form)

    except SQLAlchemyError as e:
        logger.error(f"Database error while loading university: {e}")
        flash("Error loading university. Please try again.", "error")
        return redirect(url_for("university.index"))


@bp.route("/<int:university_id>/delete", methods=["GET", "POST"])
@admin_required
def delete(university_id: int) -> str | Any:
    """
    Delete a university.

    GET: Show confirmation page
    POST: Delete university and redirect to list

    Args:
        university_id: University ID

    Returns:
        Rendered confirmation template (GET) or redirect to list (POST)
    """
    service = UniversityService()

    try:
        university = service.get_university(university_id)

        if not university:
            flash(f"University with ID {university_id} not found.", "error")
            return redirect(url_for("university.index"))

        if request.method == "GET":
            return render_template("university/delete.html", university=university)

        # POST: Delete university using service
        university_name = university.name
        if service.delete_university(university_id):
            flash(f"University '{university_name}' deleted successfully.", "success")
            return redirect(url_for("university.index"))

        flash(f"Error deleting university '{university_name}'.", "error")
        return redirect(url_for("university.show", university_id=university_id))

    except SQLAlchemyError as e:
        logger.error(f"Database error while deleting university: {e}")
        flash("Error deleting university. Please try again.", "error")
        return redirect(url_for("university.show", university_id=university_id))
