"""
University routes blueprint.

This module provides web routes for managing universities through the Flask interface.
"""

import logging
from typing import Any

from flask import Blueprint, flash, redirect, render_template, request, url_for
from sqlalchemy.exc import SQLAlchemyError

from app import db
from app.models.university import University
from app.forms.university import UniversityForm

# Configure logging
logger = logging.getLogger(__name__)

# Create blueprint
bp = Blueprint("university", __name__, url_prefix="/universities")


@bp.route("/")
def index() -> str:
    """
    List all universities with optional search.

    Query parameters:
        search: Optional search term to filter by name or slug

    Returns:
        Rendered template with list of universities
    """
    search_term = request.args.get("search", "").strip()

    try:
        query = db.session.query(University)

        if search_term:
            search_pattern = f"%{search_term}%"
            query = query.filter(
                (University.name.ilike(search_pattern))
                | (University.slug.ilike(search_pattern))
            )

        universities = query.order_by(University.name).all()

        return render_template(
            "university/list.html",
            universities=universities,
            search_term=search_term,
        )

    except SQLAlchemyError as e:
        logger.error(f"Database error while listing universities: {e}")
        flash("Error loading universities. Please try again.", "error")
        return render_template("university/list.html", universities=[], search_term="")


@bp.route("/<int:university_id>")
def show(university_id: int) -> str | Any:
    """
    Show details for a specific university.

    Args:
        university_id: University ID

    Returns:
        Rendered template with university details or 404
    """
    try:
        university = db.session.query(University).filter_by(id=university_id).first()

        if not university:
            flash(f"University with ID {university_id} not found.", "error")
            return redirect(url_for("university.index"))

        return render_template("university/detail.html", university=university)

    except SQLAlchemyError as e:
        logger.error(f"Database error while fetching university: {e}")
        flash("Error loading university details. Please try again.", "error")
        return redirect(url_for("university.index"))


@bp.route("/new", methods=["GET", "POST"])
def new() -> str | Any:
    """
    Create a new university.

    GET: Show form
    POST: Create university and redirect to detail page

    Form fields:
        name: University name (required)
        slug: URL-friendly identifier (optional, auto-generated if empty)

    Returns:
        Rendered form template (GET) or redirect to detail page (POST)
    """
    form = UniversityForm()

    if form.validate_on_submit():
        try:
            # Create new university
            university = University(
                name=form.name.data,
                slug=form.slug.data,  # slug is auto-generated by form validator if empty
            )
            db.session.add(university)
            db.session.commit()

            logger.info(f"Created university: {university.name} ({university.slug})")
            flash(f"University '{university.name}' created successfully.", "success")
            return redirect(url_for("university.show", university_id=university.id))

        except SQLAlchemyError as e:
            db.session.rollback()
            logger.error(f"Database error while creating university: {e}")
            flash("Error creating university. Please try again.", "error")

    # Display form validation errors
    for field, errors in form.errors.items():
        for error in errors:
            flash(error, "error")

    return render_template("university/form.html", university=None, form=form)


@bp.route("/<int:university_id>/edit", methods=["GET", "POST"])
def edit(university_id: int) -> str | Any:
    """
    Edit an existing university.

    GET: Show edit form
    POST: Update university and redirect to detail page

    Args:
        university_id: University ID

    Form fields:
        name: University name (required)
        slug: URL-friendly identifier (required)

    Returns:
        Rendered form template (GET) or redirect to detail page (POST)
    """
    try:
        university = db.session.query(University).filter_by(id=university_id).first()

        if not university:
            flash(f"University with ID {university_id} not found.", "error")
            return redirect(url_for("university.index"))

        form = UniversityForm(university=university, obj=university)

        if form.validate_on_submit():
            try:
                # Update fields
                university.name = form.name.data
                university.slug = form.slug.data

                db.session.commit()
                logger.info(
                    f"Updated university: {university.name} ({university.slug})"
                )
                flash(
                    f"University '{university.name}' updated successfully.", "success"
                )
                return redirect(url_for("university.show", university_id=university.id))

            except SQLAlchemyError as e:
                db.session.rollback()
                logger.error(f"Database error while updating university: {e}")
                flash("Error updating university. Please try again.", "error")

        # Display form validation errors
        for field, errors in form.errors.items():
            for error in errors:
                flash(error, "error")

        return render_template("university/form.html", university=university, form=form)

    except SQLAlchemyError as e:
        logger.error(f"Database error while loading university: {e}")
        flash("Error loading university. Please try again.", "error")
        return redirect(url_for("university.index"))


@bp.route("/<int:university_id>/delete", methods=["GET", "POST"])
def delete(university_id: int) -> str | Any:
    """
    Delete a university.

    GET: Show confirmation page
    POST: Delete university and redirect to list

    Args:
        university_id: University ID

    Returns:
        Rendered confirmation template (GET) or redirect to list (POST)
    """
    try:
        university = db.session.query(University).filter_by(id=university_id).first()

        if not university:
            flash(f"University with ID {university_id} not found.", "error")
            return redirect(url_for("university.index"))

        if request.method == "GET":
            return render_template("university/delete.html", university=university)

        # POST: Delete university
        university_name = university.name
        db.session.delete(university)
        db.session.commit()

        flash(f"University '{university_name}' deleted successfully.", "success")
        return redirect(url_for("university.index"))

    except SQLAlchemyError as e:
        db.session.rollback()
        logger.error(f"Database error while deleting university: {e}")
        flash("Error deleting university. Please try again.", "error")
        return redirect(url_for("university.show", university_id=university_id))
